# Generated by OwnCode's release workflow. Do not edit checksums manually.
class Owncode < Formula
  desc "Terminal coding agent with orchestration and context compaction"
  homepage "https://github.com/muratmirgun/owncode"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/muratmirgun/owncode/releases/download/v0.4.1/owncode-mac-arm64.tar.gz"
      sha256 "1cab83f2f0bbdcdd7eae9478115b09a48b53ffd0f33ab1c0f370c410db7cf49b"
    end
    on_intel do
      url "https://github.com/muratmirgun/owncode/releases/download/v0.4.1/owncode-mac-x86_64.tar.gz"
      sha256 "c55e504f4c90cad993d273d8eef0d14d1bc96848eaed11a067871444ce08d924"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/muratmirgun/owncode/releases/download/v0.4.1/owncode-linux-arm64.tar.gz"
      sha256 "f6d575ee83898e5483d3d106b0b7c6dc96e83cd97c2204464a5e55382fcd85ec"
    end
    on_intel do
      url "https://github.com/muratmirgun/owncode/releases/download/v0.4.1/owncode-linux-x86_64.tar.gz"
      sha256 "d1a6e12605c34ad7a44b27d5cf5dab75bc89879f21af39143e40578da5ef2947"
    end
  end

  depends_on "git"

  def install
    bin.install "owncode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/owncode --version")
  end
end
